@startuml ClassDiagram
class School {
    +name: String
    +address: String
    +openingtime: Integer
    +closingTime :Integer
}

class Student {
    +studentID: String
    +name: String
    +viewGrades(): List<Grade>
}

class Teacher {
    +teacherID: String
    +name: String
    +marks: Integer
    +subject: String
    +assignGrade(student: Student, grade: Grade): void
}

class Exams {
    +marks : Integer
    +questionpapaer : String
    +Subject: Integer
    +TotalMarks : Integer

}

class Subject {
    +SubjectID: String
    +SubjectName: String
    +Grades: Integer
    +Exams: String

}

class Grade {
    +gradeID: String
    +value: String
    
}

class Classroom {
    +roomNumber: Integer
    +capacity: Integer
}


School --> "many" Student
School --> "many" Teacher 
School --> "many" Subject 
School --> "many" Classroom 


Subject --> "taught by" Teacher 
Subject --> "includes" Grade 

Subject --> "takes" Exams

Student --> "many" Grade

@enduml